language: python

python:
  - 3.2
  - 3.3
  - 3.4

before_install:
  - sudo apt-get install libjpeg-dev
  - pip install -I pillow
  - sudo pip install nose

install: "pip install -r requirements.txt"

script: nosetests -v --with-coverage --cover-package=resize_tool