#mandatory params
source_folder: '/tmp/'
destination_folder: '/tmp/'
file_name_pattern: 'picture-$$.jpg'
file_name_pattern_seq_start_num: 0

#obligatory params
output_weight: 640
output_height: 480

copyright_text:
copyright_alpha: 80
